# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: bmanu/silverstripe-web-node:7.1-platform-java
        environment:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_DATABASE=circle_test
          - MYSQL_HOST=127.0.0.1

    working_directory: /var/www/html

    branches:
      only:
        - master
        - develop
        - /feature.*/
        - /step.*/

    steps:
      # Start apache and xvfb
      - run: /etc/init.d/apache2 start
      - run:
          command: Xvfb :99 -screen 0 1440x900x24
          background: true

      - checkout

      # download and cache composer dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-composer-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # setup silverstripe specific .env variables and update permissions
      # so website can be accessed correctly
      - run: mv .circleci/.env.circleci .env
      - run: mkdir /var/www/html/assets
      - run: chown -R www-data:www-data /var/www/html

      # setup db tables and fixtures before tests
      - run: vendor/bin/sake dev/build flush=1
      - run: vendor/bin/sake dev/tasks/DNADesign-Populate-PopulateTask

      # run php tests - no current phpunit tests
      # - run: vendor/bin/phpunit -d memory_limit=512M

      # download and cache yarn dependencies
      - restore_cache:
          keys:
            - v1-yarn-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-yarn-

      - run: yarn install

      # update google-chrome
      - run: apt-get update
      - run: apt-get --only-upgrade -y install google-chrome-stable

      # run e2e tests
      - run: yarn nightwatch --verbose

      - save_cache:
          paths:
            - ./node_modules
          key: v1-yarn-{{ checksum "yarn.lock" }}

      - store_artifacts:
          path: app/tests/nightwatch_screenshots
          destination: nightwatch_screenshots

      - store_artifacts:
          path: app/tests/nightwatch_reports
          destination: nightwatch_reports
